{% set version = "0.5.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-traits
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/traits_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/traits/traits_{{ version }}.tar.gz
  sha256: 3080887a454d69814cd6cb9683a6750db02cf4c77b40b022ef50d40171ba6aca

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-crul >=0.6.0
    - r-data.table >=1.9.6
    - r-hoardr
    - r-httr >=1.1.0
    - r-jsonlite >=0.9.19
    - r-readr >=1.1.1
    - r-rvest >=0.3.1
    - r-taxize >=0.7.4
    - r-tibble >=1.3.4
    - r-xml2 >=0.1.2
  run:
    - r-base
    - r-crul >=0.6.0
    - r-data.table >=1.9.6
    - r-hoardr
    - r-httr >=1.1.0
    - r-jsonlite >=0.9.19
    - r-readr >=1.1.1
    - r-rvest >=0.3.1
    - r-taxize >=0.7.4
    - r-tibble >=1.3.4
    - r-xml2 >=0.1.2

test:
  commands:
    - $R -e "library('traits')"           # [not win]
    - "\"%R%\" -e \"library('traits')\""  # [win]

about:
  home: https://github.com/ropensci/traits
  license: MIT
  summary: Species trait data from many different sources, including sequence data from 'NCBI', plant trait data from 'BETYdb', plant data from the USDA plants database, data from 'EOL' 'Traitbank', Coral traits data (<https://coraltraits.org>), 'Birdlife' International, and more.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - brendanf

# Package: traits
# Title: Species Trait Data from Around the Web
# Description: Species trait data from many different sources, including sequence data from 'NCBI', plant trait data from 'BETYdb', plant data from the USDA plants database, data from 'EOL' 'Traitbank', Coral traits data (<https://coraltraits.org>), 'Birdlife' International, and more.
# Version: 0.4.2
# Authors@R: c( person("Scott", "Chamberlain", role = c("aut", "cre"), email = "myrmecocystus@gmail.com"), person("Zachary", "Foster", role = "aut"), person("Ignasi", "Bartomeus", role = "aut"), person("David", "LeBauer", role = "aut"), person("Chris", "Black", role = "aut"), person("David", "Harris", role = "aut"), person("Rupert", "Collins", role = "ctb") )
# License: MIT + file LICENSE
# URL: https://github.com/ropensci/traits
# BugReports: https://github.com/ropensci/traits/issues
# LazyData: true
# Encoding: UTF-8
# VignetteBuilder: knitr
# Depends: R (>= 2.10)
# Imports: jsonlite (>= 0.9.19), httr (>= 1.1.0), crul (>= 0.6.0), tibble (>= 1.3.4), data.table (>= 1.9.6), readr (>= 1.1.1), taxize (>= 0.7.4), xml2 (>= 0.1.2), rvest (>= 0.3.1), hoardr
# Suggests: roxygen2 (>= 6.0.1), knitr, testthat, dplyr, plyr
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2019-06-29 01:25:29 UTC; sckott
# Author: Scott Chamberlain [aut, cre], Zachary Foster [aut], Ignasi Bartomeus [aut], David LeBauer [aut], Chris Black [aut], David Harris [aut], Rupert Collins [ctb]
# Maintainer: Scott Chamberlain <myrmecocystus@gmail.com>
# Repository: CRAN
# Date/Publication: 2019-06-29 05:00:03 UTC
